apiVersion: v1
kind: Service
metadata:
  name: {{ template "servicemonitor.fullname" . }}
  labels:
    app: {{ template "servicemonitor.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.namespaceSelector }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "{{ .Values.metricsPortName }}"
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
