module: http_2xx
namespace: prometheus-blackbox
blackboxexporter:
  - serviceName: prometheus-blackbox-kube-p-blackbox-exporter
    namespace: prometheus-blackbox
    port: 19115
targets:
  - "https://api.app.com/api/v2/actuator/health"

relabelings:
  - targetLabel: env
    replacement: "env-example"
  - targetLabel: host
    replacement: "host-example"

